packages: []

catalogs:

  build:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/lucide': ^1.2.42
    '@vitejs/plugin-vue': ^5.2.4

    jsdom: ^26.1.0
    tinyexec: ^1.0.1
    unocss: ^66.1.1
    unplugin: ^2.3.3
    unplugin-auto-import: ^19.2.0
    unplugin-vue-components: ^28.5.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.12.0
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.13.0
    '@antfu/ni': ^24.3.0
    '@types/node': ^22.15.17
    '@unocss/eslint-plugin': ^66.1.1
    '@vue-macros/volar': ^3.0.0-beta.12
    '@vue/test-utils': ^2.4.6
    eslint: ^9.26.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    typescript: ^5.8.3
    vitest: ^3.1.3
    vue-tsc: ^2.2.10

  frontend:
    '@vueuse/components': ^13.1.0
    '@vueuse/core': ^13.1.0
    vue: ^3.5.13
    vue-router: ^4.5.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
